"""Initial schema

Revision ID: 069a5acffa33
Revises: 
Create Date: 2026-01-03 11:08:53.033124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069a5acffa33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('printers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('moonraker_url', sa.String(length=500), nullable=False),
    sa.Column('moonraker_api_key', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_printers_name'), ['name'], unique=True)

    op.create_table('job_totals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=False),
    sa.Column('total_print_time', sa.Float(), nullable=False),
    sa.Column('total_filament_used', sa.Float(), nullable=False),
    sa.Column('longest_job', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printer_id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('print_duration', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('filament_used', sa.Float(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('auxiliary_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_printer_job', ['printer_id', 'job_id'], unique=True)
        batch_op.create_index('idx_printer_status', ['printer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_jobs_status'), ['status'], unique=False)

    op.create_table('job_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('layer_height', sa.Float(), nullable=True),
    sa.Column('first_layer_height', sa.Float(), nullable=True),
    sa.Column('nozzle_temp', sa.Integer(), nullable=True),
    sa.Column('bed_temp', sa.Integer(), nullable=True),
    sa.Column('print_speed', sa.Integer(), nullable=True),
    sa.Column('infill_percentage', sa.Integer(), nullable=True),
    sa.Column('infill_pattern', sa.String(length=50), nullable=True),
    sa.Column('support_enabled', sa.Boolean(), nullable=True),
    sa.Column('support_type', sa.String(length=50), nullable=True),
    sa.Column('filament_type', sa.String(length=50), nullable=True),
    sa.Column('filament_brand', sa.String(length=100), nullable=True),
    sa.Column('filament_color', sa.String(length=50), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('estimated_filament', sa.Float(), nullable=True),
    sa.Column('layer_count', sa.Integer(), nullable=True),
    sa.Column('object_height', sa.Float(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('print_job_id')
    )
    with op.batch_alter_table('job_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_details_filament_type'), ['filament_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_details_filament_type'))

    op.drop_table('job_details')
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_print_jobs_start_time'))
        batch_op.drop_index('idx_printer_status')
        batch_op.drop_index('idx_printer_job')

    op.drop_table('print_jobs')
    op.drop_table('job_totals')
    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printers_name'))
        batch_op.drop_index(batch_op.f('ix_printers_is_active'))

    op.drop_table('printers')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_is_active'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
