"""add_maintenance_records

Revision ID: 2ea79be9c026
Revises: fefc3bcb1be0
Create Date: 2026-01-09 20:56:32.271252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea79be9c026'
down_revision: Union[str, Sequence[str], None] = 'fefc3bcb1be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index('idx_printer_maintenance_date', ['printer_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_done'), ['done'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_done'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_date'))
        batch_op.drop_index('idx_printer_maintenance_date')

    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
