"""add_thumbnail_to_job_details

Revision ID: 395156864048
Revises: 069a5acffa33
Create Date: 2026-01-05 20:04:37.923626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395156864048'
down_revision: Union[str, Sequence[str], None] = '069a5acffa33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_base64', sa.String(length=100000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_details', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_base64')

    # ### end Alembic commands ###
