"""add_slicer_and_filament_metadata

Revision ID: ypdqxrr704l1
Revises: 395156864048
Create Date: 2026-01-07 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ypdqxrr704l1'
down_revision: Union[str, Sequence[str], None] = '395156864048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add slicer info and enhanced filament metadata."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_details', schema=None) as batch_op:
        # Slicer information
        batch_op.add_column(sa.Column('slicer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('slicer_version', sa.String(length=50), nullable=True))

        # Multi-filament usage arrays
        batch_op.add_column(sa.Column('filament_used_mm', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('filament_used_cm3', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('filament_used_g', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('filament_cost', sa.JSON(), nullable=True))

        # Total values
        batch_op.add_column(sa.Column('total_filament_used_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_filament_cost', sa.Float(), nullable=True))

        # Full config block
        batch_op.add_column(sa.Column('config_block', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove slicer info and enhanced filament metadata."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_details', schema=None) as batch_op:
        batch_op.drop_column('config_block')
        batch_op.drop_column('total_filament_cost')
        batch_op.drop_column('total_filament_used_g')
        batch_op.drop_column('filament_cost')
        batch_op.drop_column('filament_used_g')
        batch_op.drop_column('filament_used_cm3')
        batch_op.drop_column('filament_used_mm')
        batch_op.drop_column('slicer_version')
        batch_op.drop_column('slicer_name')

    # ### end Alembic commands ###
