"""Tests for OrcaSlicer gcode metadata parser."""

import pytest
from pathlib import Path

from src.gcode.parser import GcodeParser, GcodeMetadata


# Sample gcode content for unit tests
SAMPLE_HEADER = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1-dev on 2026-01-05 at 08:58:14
; total layer number: 70
; filament_density: 1.25,1.25,1.25,1.25
; filament_diameter: 1.75,1.75,1.75,1.75
; max_z_height: 14.00
; HEADER_BLOCK_END
"""

SAMPLE_CONFIG = """; layer_height = 0.2
; initial_layer_print_height = 0.25
; nozzle_temperature = 220,220,220,220
; hot_plate_temp = 55,55,55,55
; filament_type = PLA;PLA;PLA;PLA
; filament_colour = #780017;#FFFFFF;#F4E2C1;#ED1C24
; sparse_infill_density = 15%
; sparse_infill_pattern = gyroid
; support_type = normal(auto)
; outer_wall_speed = 200
; inner_wall_speed = 300
; estimated printing time (normal mode) = 40m 34s
; filament used [g] = 9.85, 12.27, 0.00, 0.00
; total layers count = 70
"""


class TestGcodeMetadata:
    """Test GcodeMetadata dataclass."""

    def test_metadata_with_all_fields(self):
        """Create metadata with all fields populated."""
        metadata = GcodeMetadata(
            layer_height=0.2,
            first_layer_height=0.25,
            nozzle_temp=220,
            bed_temp=55,
            print_speed=200,
            infill_percentage=15,
            infill_pattern="gyroid",
            support_enabled=True,
            support_type="normal(auto)",
            filament_type="PLA",
            filament_color="#780017",
            estimated_time=2434,
            estimated_filament=9.85,
            layer_count=70,
            object_height=14.0,
            slicer_name="OrcaSlicer",
            slicer_version="2.3.1-dev",
        )
        assert metadata.layer_height == 0.2
        assert metadata.nozzle_temp == 220
        assert metadata.filament_type == "PLA"

    def test_metadata_with_minimal_fields(self):
        """Create metadata with only required fields."""
        metadata = GcodeMetadata()
        assert metadata.layer_height is None
        assert metadata.nozzle_temp is None

    def test_metadata_to_dict(self):
        """Convert metadata to dictionary."""
        metadata = GcodeMetadata(layer_height=0.2, nozzle_temp=220)
        result = metadata.to_dict()
        assert isinstance(result, dict)
        assert result["layer_height"] == 0.2
        assert result["nozzle_temp"] == 220


class TestGcodeParser:
    """Test GcodeParser class."""

    def test_parser_initialization(self):
        """Parser can be initialized."""
        parser = GcodeParser()
        assert parser is not None

    def test_parse_empty_content(self):
        """Parsing empty content returns empty metadata."""
        parser = GcodeParser()
        result = parser.parse("")
        assert isinstance(result, GcodeMetadata)

    def test_parse_layer_height(self):
        """Parse layer height from config."""
        parser = GcodeParser()
        result = parser.parse("; layer_height = 0.2\n")
        assert result.layer_height == 0.2

    def test_parse_first_layer_height(self):
        """Parse first layer height from config."""
        parser = GcodeParser()
        result = parser.parse("; initial_layer_print_height = 0.25\n")
        assert result.first_layer_height == 0.25

    def test_parse_nozzle_temp(self):
        """Parse nozzle temperature (first extruder)."""
        parser = GcodeParser()
        result = parser.parse("; nozzle_temperature = 220,220,220,220\n")
        assert result.nozzle_temp == 220

    def test_parse_bed_temp(self):
        """Parse bed temperature (first value)."""
        parser = GcodeParser()
        result = parser.parse("; hot_plate_temp = 55,55,55,55\n")
        assert result.bed_temp == 55

    def test_parse_filament_type(self):
        """Parse filament type (first extruder)."""
        parser = GcodeParser()
        result = parser.parse("; filament_type = PLA;PLA;PLA;PLA\n")
        assert result.filament_type == "PLA"

    def test_parse_filament_type_single(self):
        """Parse filament type with single extruder."""
        parser = GcodeParser()
        result = parser.parse("; filament_type = PETG\n")
        assert result.filament_type == "PETG"

    def test_parse_filament_color(self):
        """Parse filament color (first extruder)."""
        parser = GcodeParser()
        result = parser.parse("; filament_colour = #780017;#FFFFFF\n")
        assert result.filament_color == "#780017"

    def test_parse_infill_percentage(self):
        """Parse infill percentage."""
        parser = GcodeParser()
        result = parser.parse("; sparse_infill_density = 15%\n")
        assert result.infill_percentage == 15

    def test_parse_infill_pattern(self):
        """Parse infill pattern."""
        parser = GcodeParser()
        result = parser.parse("; sparse_infill_pattern = gyroid\n")
        assert result.infill_pattern == "gyroid"

    def test_parse_support_type_enabled(self):
        """Parse support type when enabled."""
        parser = GcodeParser()
        result = parser.parse("; support_type = normal(auto)\n")
        assert result.support_enabled is True
        assert result.support_type == "normal(auto)"

    def test_parse_support_type_disabled(self):
        """Parse support type when disabled."""
        parser = GcodeParser()
        result = parser.parse("; support_type = none\n")
        assert result.support_enabled is False
        assert result.support_type == "none"

    def test_parse_print_speed(self):
        """Parse print speed from outer wall speed."""
        parser = GcodeParser()
        result = parser.parse("; outer_wall_speed = 200\n")
        assert result.print_speed == 200

    def test_parse_estimated_time_minutes_seconds(self):
        """Parse estimated time in minutes and seconds."""
        parser = GcodeParser()
        result = parser.parse("; estimated printing time (normal mode) = 40m 34s\n")
        assert result.estimated_time == 2434  # 40*60 + 34

    def test_parse_estimated_time_hours_minutes(self):
        """Parse estimated time with hours."""
        parser = GcodeParser()
        result = parser.parse("; estimated printing time (normal mode) = 2h 30m 15s\n")
        assert result.estimated_time == 9015  # 2*3600 + 30*60 + 15

    def test_parse_estimated_time_days(self):
        """Parse estimated time with days."""
        parser = GcodeParser()
        result = parser.parse("; estimated printing time (normal mode) = 1d 2h 30m\n")
        assert result.estimated_time == 95400  # 1*86400 + 2*3600 + 30*60

    def test_parse_estimated_filament(self):
        """Parse estimated filament usage in grams."""
        parser = GcodeParser()
        result = parser.parse("; filament used [g] = 9.85, 12.27, 0.00, 0.00\n")
        assert result.estimated_filament == pytest.approx(9.85)

    def test_parse_layer_count_from_header(self):
        """Parse layer count from header block."""
        parser = GcodeParser()
        result = parser.parse("; total layer number: 70\n")
        assert result.layer_count == 70

    def test_parse_layer_count_from_config(self):
        """Parse layer count from config section."""
        parser = GcodeParser()
        result = parser.parse("; total layers count = 70\n")
        assert result.layer_count == 70

    def test_parse_object_height(self):
        """Parse object height from header."""
        parser = GcodeParser()
        result = parser.parse("; max_z_height: 14.00\n")
        assert result.object_height == pytest.approx(14.0)

    def test_parse_slicer_info(self):
        """Parse slicer name and version from header."""
        parser = GcodeParser()
        result = parser.parse("; generated by OrcaSlicer 2.3.1-dev on 2026-01-05 at 08:58:14\n")
        assert result.slicer_name == "OrcaSlicer"
        assert result.slicer_version == "2.3.1-dev"

    def test_parse_combined_content(self):
        """Parse combined header and config content."""
        parser = GcodeParser()
        content = SAMPLE_HEADER + "\n; GCODE CONTENT\n" + SAMPLE_CONFIG
        result = parser.parse(content)

        assert result.layer_height == 0.2
        assert result.first_layer_height == 0.25
        assert result.nozzle_temp == 220
        assert result.bed_temp == 55
        assert result.filament_type == "PLA"
        assert result.filament_color == "#780017"
        assert result.infill_percentage == 15
        assert result.infill_pattern == "gyroid"
        assert result.support_enabled is True
        assert result.support_type == "normal(auto)"
        assert result.estimated_time == 2434
        assert result.estimated_filament == pytest.approx(9.85)
        assert result.layer_count == 70
        assert result.object_height == pytest.approx(14.0)
        assert result.slicer_name == "OrcaSlicer"
        assert result.slicer_version == "2.3.1-dev"


class TestParseFromFile:
    """Test parsing from file paths."""

    def test_parse_file_not_found(self):
        """Raise error for non-existent file."""
        parser = GcodeParser()
        with pytest.raises(FileNotFoundError):
            parser.parse_file(Path("/nonexistent/file.gcode"))

    def test_parse_file_returns_metadata(self, tmp_path):
        """Parse file returns GcodeMetadata."""
        gcode_file = tmp_path / "test.gcode"
        gcode_file.write_text("; layer_height = 0.2\n; nozzle_temperature = 210,210\n")

        parser = GcodeParser()
        result = parser.parse_file(gcode_file)

        assert isinstance(result, GcodeMetadata)
        assert result.layer_height == 0.2
        assert result.nozzle_temp == 210


class TestIntegrationWithSampleFiles:
    """Integration tests with actual sample gcode files."""

    @pytest.fixture
    def samples_dir(self):
        """Get the samples directory."""
        project_root = Path(__file__).parent.parent.parent
        return project_root / "samples"

    def test_parse_player_tray_lid(self, samples_dir):
        """Parse the Player Tray Lid sample file."""
        sample_file = samples_dir / "Player Tray Lid_PLA_40m34s.gcode"
        if not sample_file.exists():
            pytest.skip("Sample file not found")

        parser = GcodeParser()
        result = parser.parse_file(sample_file)

        # Verify key fields extracted
        assert result.layer_height == 0.2
        assert result.first_layer_height == 0.2  # initial_layer_print_height
        assert result.nozzle_temp == 220
        assert result.bed_temp == 55
        assert result.filament_type == "PLA"
        assert result.infill_percentage == 15
        assert result.infill_pattern == "gyroid"
        assert result.layer_count == 70
        assert result.object_height == pytest.approx(14.0)
        assert result.slicer_name == "OrcaSlicer"
        assert "2.3.1" in result.slicer_version

    def test_parse_all_sample_files(self, samples_dir):
        """Parse all gcode files in samples directory."""
        if not samples_dir.exists():
            pytest.skip("Samples directory not found")

        parser = GcodeParser()
        gcode_files = list(samples_dir.glob("*.gcode"))

        assert len(gcode_files) > 0, "No gcode files found"

        for gcode_file in gcode_files:
            result = parser.parse_file(gcode_file)
            # All files should produce valid metadata
            assert isinstance(result, GcodeMetadata)
            # OrcaSlicer files should have layer height
            assert result.layer_height is not None


class TestEdgeCases:
    """Test edge cases and error handling."""

    def test_malformed_value(self):
        """Handle malformed values gracefully."""
        parser = GcodeParser()
        result = parser.parse("; layer_height = notanumber\n")
        assert result.layer_height is None  # Should not crash

    def test_missing_equals_sign(self):
        """Handle lines without equals sign."""
        parser = GcodeParser()
        parser.parse("; layer_height 0.2\n")
        # Should not crash, just not parse this line
        # (unless it's a header format like "; total layer number: 70")

    def test_unicode_content(self):
        """Handle unicode in gcode."""
        parser = GcodeParser()
        result = parser.parse("; filament_type = PLA™\n")
        assert result.filament_type == "PLA™"

    def test_windows_line_endings(self):
        """Handle Windows CRLF line endings."""
        parser = GcodeParser()
        result = parser.parse("; layer_height = 0.2\r\n; nozzle_temperature = 215\r\n")
        assert result.layer_height == 0.2
        assert result.nozzle_temp == 215

    def test_extra_whitespace(self):
        """Handle extra whitespace in values."""
        parser = GcodeParser()
        result = parser.parse(";  layer_height  =  0.2  \n")
        assert result.layer_height == 0.2


class TestThumbnailExtraction:
    """Test thumbnail extraction from gcode files."""

    # Sample thumbnail block (minimal valid PNG in base64)
    SAMPLE_THUMBNAIL_BLOCK = """; THUMBNAIL_BLOCK_START
;
; thumbnail begin 160x160 100
; iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk
; +M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END
"""

    SAMPLE_SMALL_THUMBNAIL_BLOCK = """; THUMBNAIL_BLOCK_START
;
; thumbnail begin 112x112 50
; c21hbGxlcl90aHVtYm5haWxfZGF0YQ==
; thumbnail end
; THUMBNAIL_BLOCK_END
"""

    def test_metadata_has_thumbnail_field(self):
        """GcodeMetadata should have thumbnail_base64 field."""
        metadata = GcodeMetadata()
        assert hasattr(metadata, "thumbnail_base64")
        assert metadata.thumbnail_base64 is None

    def test_metadata_with_thumbnail(self):
        """Create metadata with thumbnail populated."""
        metadata = GcodeMetadata(thumbnail_base64="iVBORw0KGgo=")
        assert metadata.thumbnail_base64 == "iVBORw0KGgo="

    def test_thumbnail_in_to_dict(self):
        """Thumbnail should be included in to_dict output."""
        metadata = GcodeMetadata(thumbnail_base64="test_data")
        result = metadata.to_dict()
        assert "thumbnail_base64" in result
        assert result["thumbnail_base64"] == "test_data"

    def test_extract_thumbnail_from_gcode(self):
        """Extract thumbnail from gcode content."""
        parser = GcodeParser()
        content = "; layer_height = 0.2\n" + self.SAMPLE_THUMBNAIL_BLOCK
        result = parser.parse(content)
        assert result.thumbnail_base64 is not None
        # Should contain the base64 data without comment prefixes
        assert "iVBORw0KGgo" in result.thumbnail_base64

    def test_no_thumbnail_returns_none(self):
        """Gcode without thumbnail returns None."""
        parser = GcodeParser()
        result = parser.parse("; layer_height = 0.2\n")
        assert result.thumbnail_base64 is None

    def test_select_largest_thumbnail(self):
        """When multiple thumbnails exist, select the largest."""
        parser = GcodeParser()
        # Large thumbnail first
        content = self.SAMPLE_THUMBNAIL_BLOCK + self.SAMPLE_SMALL_THUMBNAIL_BLOCK
        result = parser.parse(content)
        assert result.thumbnail_base64 is not None
        # Should contain the larger 160x160 thumbnail data
        assert "iVBORw0KGgo" in result.thumbnail_base64

    def test_select_largest_thumbnail_reversed_order(self):
        """Select largest thumbnail regardless of order in file."""
        parser = GcodeParser()
        # Small thumbnail first, large second
        content = self.SAMPLE_SMALL_THUMBNAIL_BLOCK + self.SAMPLE_THUMBNAIL_BLOCK
        result = parser.parse(content)
        assert result.thumbnail_base64 is not None
        # Should still contain the larger 160x160 thumbnail
        assert "iVBORw0KGgo" in result.thumbnail_base64

    def test_thumbnail_strips_comment_prefix(self):
        """Base64 data should not include comment prefixes."""
        parser = GcodeParser()
        result = parser.parse(self.SAMPLE_THUMBNAIL_BLOCK)
        if result.thumbnail_base64:
            assert not result.thumbnail_base64.startswith(";")
            assert "; " not in result.thumbnail_base64

    def test_thumbnail_from_sample_file(self):
        """Extract thumbnail from actual sample gcode file."""
        parser = GcodeParser()
        samples_dir = Path(__file__).parent.parent.parent / "samples"
        gcode_files = list(samples_dir.glob("*.gcode"))

        if gcode_files:
            result = parser.parse_file(gcode_files[0])
            # OrcaSlicer files should have thumbnails
            assert result.thumbnail_base64 is not None
            # Should be valid base64 PNG (starts with PNG header in base64)
            assert result.thumbnail_base64.startswith("iVBORw0KGgo")


class TestFilamentMetadataExtraction:
    """Test extraction of filament usage and cost metadata (Issue #5)."""

    def test_parse_filament_used_mm_multi_extruder(self):
        """Parse filament used in millimeters (multi-extruder)."""
        parser = GcodeParser()
        result = parser.parse("; filament used [mm] = 3274.48, 4080.36, 0.00, 0.00\n")
        assert result.filament_used_mm == [3274.48, 4080.36, 0.00, 0.00]

    def test_parse_filament_used_cm3(self):
        """Parse filament used in cubic centimeters."""
        parser = GcodeParser()
        result = parser.parse("; filament used [cm3] = 7.88, 9.81, 0.00, 0.00\n")
        assert result.filament_used_cm3 == [7.88, 9.81, 0.00, 0.00]

    def test_parse_filament_used_g_multi_extruder(self):
        """Parse filament used in grams (multi-extruder)."""
        parser = GcodeParser()
        result = parser.parse("; filament used [g] = 9.85, 12.27, 0.00, 0.00\n")
        assert result.filament_used_g == [9.85, 12.27, 0.00, 0.00]

    def test_parse_filament_cost_multi_extruder(self):
        """Parse per-extruder filament cost."""
        parser = GcodeParser()
        result = parser.parse("; filament cost = 0.23, 0.28, 0.00, 0.00\n")
        assert result.filament_cost == [0.23, 0.28, 0.00, 0.00]

    def test_parse_total_filament_used_g(self):
        """Parse total filament used across all extruders."""
        parser = GcodeParser()
        result = parser.parse("; total filament used [g] = 22.11\n")
        assert result.total_filament_used_g == pytest.approx(22.11)

    def test_parse_total_filament_cost(self):
        """Parse total filament cost across all extruders."""
        parser = GcodeParser()
        result = parser.parse("; total filament cost = 0.51\n")
        assert result.total_filament_cost == pytest.approx(0.51)

    def test_filament_used_mm_single_extruder(self):
        """Parse filament data for single-extruder setup."""
        parser = GcodeParser()
        result = parser.parse("; filament used [mm] = 2500.5\n")
        assert result.filament_used_mm == [2500.5]

    def test_filament_arrays_in_to_dict(self):
        """Filament arrays should be included in to_dict output."""
        metadata = GcodeMetadata(
            filament_used_mm=[3274.48, 4080.36],
            filament_used_cm3=[7.88, 9.81],
            filament_used_g=[9.85, 12.27],
            filament_cost=[0.23, 0.28]
        )
        result = metadata.to_dict()
        assert result["filament_used_mm"] == [3274.48, 4080.36]
        assert result["filament_used_cm3"] == [7.88, 9.81]
        assert result["filament_used_g"] == [9.85, 12.27]
        assert result["filament_cost"] == [0.23, 0.28]


class TestConfigBlockExtraction:
    """Test extraction of full config block (Issue #5)."""

    def test_extract_config_block_basic(self):
        """Extract config block between markers."""
        gcode = """; CONFIG_BLOCK_START
; layer_height = 0.2
; nozzle_temperature = 220,220,220,220
; bed_temp = 55
; CONFIG_BLOCK_END
"""
        parser = GcodeParser()
        result = parser.parse(gcode)
        assert result.config_block is not None
        assert result.config_block["layer_height"] == "0.2"
        assert result.config_block["nozzle_temperature"] == "220,220,220,220"
        assert result.config_block["bed_temp"] == "55"

    def test_config_block_with_many_settings(self):
        """Config block handles many settings (100+)."""
        gcode = "; CONFIG_BLOCK_START\n"
        # Add 150 settings
        for i in range(150):
            gcode += f"; setting_{i} = value_{i}\n"
        gcode += "; CONFIG_BLOCK_END\n"

        parser = GcodeParser()
        result = parser.parse(gcode)
        assert result.config_block is not None
        assert len(result.config_block) == 150
        assert result.config_block["setting_0"] == "value_0"
        assert result.config_block["setting_149"] == "value_149"

    def test_config_block_with_complex_values(self):
        """Config block handles complex value formats."""
        gcode = """; CONFIG_BLOCK_START
; wipe_tower_x = 165,165,165,165,165,165,165,165
; small_area_infill_flow_compensation_model = 0,0;"\\n0.2,0.4444"
; filament_settings_id = "eSUN PLA+ @BBL X1C(Test.3mf)"
; CONFIG_BLOCK_END
"""
        parser = GcodeParser()
        result = parser.parse(gcode)
        assert result.config_block is not None
        assert "wipe_tower_x" in result.config_block
        assert "small_area_infill_flow_compensation_model" in result.config_block
        assert "filament_settings_id" in result.config_block

    def test_no_config_block_returns_none(self):
        """Return None when no config block present."""
        parser = GcodeParser()
        result = parser.parse("; layer_height = 0.2\n")
        assert result.config_block is None

    def test_config_block_ignores_non_config_lines(self):
        """Config block only captures lines within markers."""
        gcode = """; before_config = should_ignore
; CONFIG_BLOCK_START
; inside_config = should_capture
; CONFIG_BLOCK_END
; after_config = should_ignore
"""
        parser = GcodeParser()
        result = parser.parse(gcode)
        assert result.config_block is not None
        assert "inside_config" in result.config_block
        assert "before_config" not in result.config_block
        assert "after_config" not in result.config_block

    def test_config_block_in_to_dict(self):
        """Config block should be included in to_dict output."""
        metadata = GcodeMetadata(
            config_block={"layer_height": "0.2", "bed_temp": "55"}
        )
        result = metadata.to_dict()
        assert "config_block" in result
        assert result["config_block"]["layer_height"] == "0.2"


class TestSlicerInfoStorage:
    """Test that slicer name and version are now stored (Issue #5)."""

    def test_slicer_info_in_to_dict(self):
        """Slicer info included in to_dict output."""
        metadata = GcodeMetadata(
            slicer_name="OrcaSlicer",
            slicer_version="2.3.1-dev"
        )
        result = metadata.to_dict()
        assert "slicer_name" in result
        assert "slicer_version" in result
        assert result["slicer_name"] == "OrcaSlicer"
        assert result["slicer_version"] == "2.3.1-dev"

    def test_slicer_fields_exist_on_metadata(self):
        """GcodeMetadata has slicer fields."""
        metadata = GcodeMetadata()
        assert hasattr(metadata, "slicer_name")
        assert hasattr(metadata, "slicer_version")

    def test_combined_extraction_with_new_fields(self):
        """Parse combined content with all new fields."""
        gcode = """; generated by OrcaSlicer 2.3.1-dev on 2026-01-05 at 08:58:14
; filament used [mm] = 3274.48, 4080.36, 0.00, 0.00
; filament used [cm3] = 7.88, 9.81, 0.00, 0.00
; filament used [g] = 9.85, 12.27, 0.00, 0.00
; filament cost = 0.23, 0.28, 0.00, 0.00
; total filament used [g] = 22.12
; total filament cost = 0.51
; CONFIG_BLOCK_START
; layer_height = 0.2
; bed_temp = 55
; CONFIG_BLOCK_END
"""
        parser = GcodeParser()
        result = parser.parse(gcode)

        # Verify all new fields extracted
        assert result.slicer_name == "OrcaSlicer"
        assert result.slicer_version == "2.3.1-dev"
        assert result.filament_used_mm == [3274.48, 4080.36, 0.00, 0.00]
        assert result.filament_used_cm3 == [7.88, 9.81, 0.00, 0.00]
        assert result.filament_used_g == [9.85, 12.27, 0.00, 0.00]
        assert result.filament_cost == [0.23, 0.28, 0.00, 0.00]
        assert result.total_filament_used_g == pytest.approx(22.12)
        assert result.total_filament_cost == pytest.approx(0.51)
        assert result.config_block is not None
        assert result.config_block["layer_height"] == "0.2"
